services:
  web:
    build: .
    container_name: yt-downloader-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - YT_API_KEY=${YT_API_KEY}
    volumes:
      - ./tmp:/tmp
    # healthcheck simples
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
